apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: app:latest
          volumeMounts:
            - name: host-root
              mountPath: /host
          securityContext:
            privileged: true
      volumes:
        - name: host-root
          hostPath:
            path: /
